config/routes.rb
Rails.application.routes.draw do

  root to: redirect('/compound_interest')

  resource :compound_interest, only: [:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/compound_interest.rb
class CompoundInterest

  include ActiveModel::Model

  attr_accessor :current_principal, :years_to_grow, :interest_rate,:annual_addition

  attr_reader :result

  validates :current_principal, :years_to_grow, :interest_rate, presence: true
  validates :current_principal, :years_to_grow, :interest_rate, numericality: { greater_than: 0 }

  def submit
    return false if invalid?
    @result = calculate_result
    true
  end

  private

  def calculate_result
    future_value_of_principal+future_value_of_additions
  end

  def future_value_of_principal
    current_principal.to_d * (1 + interest_rate.to_d / 100 / 12) ** (years_to_grow.to_d * 12)
  end

  def future_value_of_additions
    annual_addition.to_d * ((1 + interest_rate.to_d / 100 / 12) ** (years_to_grow.to_d * 12) - 1) / (interest_rate.to_d / 100)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/compound_interests_controller.rb
class CompoundInterestsController < ApplicationController

  def show
    @compound_interest = CompoundInterest.new(compound_interest_params)
    @compound_interest.submit unless compound_interest_params.empty?
  end

  private

  def compound_interest_params
    params.fetch(:compound_interest, {}).permit(:current_principal, :years_to_grow, :interest_rate, :annual_addition)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/compound_interests_helper.rb
module CompoundInterestsHelper
end

app/views/compound_interests/show.html.erb
<div class='container'>

  <div class='card mt-5'>
    <%= simple_form_for @compound_interest, url: compound_interest_path, method: :get do |f| %>
      <div class='card-header'>
        <strong class='card-title mb-0'>Compound Interest Calculator</strong>
      </div>

      <div class='card-body'>
        <%= f.input :current_principal %>
        <%= f.input :years_to_grow %>
        <%= f.input :interest_rate %>
        <%= f.input :annual_addition %>
      </div>

      <div class='card-footer d-flex justify-content-between'>

        <%= f.submit 'Calculate', class: 'btn btn-primary' %>

        <%- if @compound_interest.result.present? %>
          <div class='text-center input-label'>
            <span>Future Value</span>
            <strong><%= number_to_currency @compound_interest.result %></strong>
          </div>
        <%- end %>

      </div>

    <%- end %>

  </div>


</div>
<p> test change </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceDemos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>